### ISSUE TITLE
포메터가 없는데 이유가 있으신가요?

### ISSUE THREAD

**Issue by minsoo-web** [coauthors/coauthors#1]
biome 가 포메터 역할도 해주는지 궁금합니다. 클론 받고 수정 좀 해봤는데 포메팅이 안 되는 것 같아서 문의 드립니다!

**Comment by 2-NOW** [comment]
The biome does the formatter job for you :D You can check it out here.
https://biomejs.dev/formatter

**Comment by minsoo-web** [comment]
This issue was due to me not using the vscode extension of biomejs. I'll close it!
