### ISSUE TITLE
Do we need Logo simply?

### ISSUE THREAD

**Issue by manudeli** [coauthors/coauthors#36]
I agree with the logo. I think it looks good without too much meaning, but I feel like it might be too generic and not represent the library's brand. I'm not an expert on this point, so please tread lightly.

@manudeli

_Originally posted by @2-NOW in https://github.com/coauthors/coauthors/issues/32#issuecomment-2068081399_

**Comment by 2-NOW** [comment]
FYI) I agree that it's a simple change to the logo. I was thinking it would be better if the logo showed the identity.

**Comment by manudeli** [comment]
I did it first. We can also change this gradually.
