### ISSUE TITLE
[Feature]: New Coauthors bot

### ISSUE THREAD

**Issue by manudeli** [coauthors/coauthors#69]
### Package Scope

etc

### Description

In Pull Request, fetch all conversation participants could be co-author!

Idea by @sungh0lim

**Comment by manudeli** [comment]
@2-NOW I'll make it as bot like changesets early to support all converstion participants's efforts

**Comment by 2-NOW** [comment]
> @2-NOW I'll make it as bot like changesets early to support all converstion participants's efforts

I think it's a very good attempt!

**Comment by manudeli** [comment]
I will make bot commenter like changesets

> click to add converstion contributor @sungh0lim as co-author

**Comment by juno7803** [comment]
Great Idea! It would be very useful 🚀

**Comment by manudeli** [comment]
/coauthors @manudeli

Command by comment

**Comment by manudeli** [comment]
Coauthor bot is released from now

<img width="923" alt="image" src="https://github.com/user-attachments/assets/461049d4-6d19-4de4-aa06-a4aad814ac06">

**Comment by manudeli** [comment]
@sungh0lim @2-NOW @juno7803
Thank you for discussing the idea with me and making it concrete!

I added you guys as co-authors in [5e682f6](https://github.com/coauthors/coauthors/commit/5e682f6f89c717634e2447db29e215f20574741b)
