### ISSUE TITLE
[Feature]: Consider designating "co:" as an abbreviation for "coauthors:"

### ISSUE THREAD

**Issue by SEOKKAMONI** [coauthors/coauthors#76]
### Package Scope

etc

### Description

When specifying coauthors through commits, typing the coauthors: command each time and adding the GitHub ID of the coauthor feels somewhat burdensome.

So, I would like to suggest that many users might find the coauthors command psychologically lengthy. To alleviate this burden, how about allowing the use of a shorter alias like co: to specify coauthors, as shown below?

```bash
git commit -m "chore: add test code

co: SEOKKAMONI"
```

**Comment by manudeli** [comment]
Thanks for the great idea

For now, I'm going to keep the keyword coauthors:. I think we need to push the keyword coauthors, even though it's not familiar to users yet. I expect that consistent interface names will make it easier for users to understand.
